[package]
name = "eggsh"
version = "0.1.1"
edition = "2024"
description = "yolkiest shell out there"
readme-file = "README.md"
license-file = "LICENSE.md"

[dependencies]
crossterm = "0.29.0"
dirs = "6.0.0"
